[package]
name = "core_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
# 1. Giao diện (Đã gỡ bỏ tính năng web, dùng chuẩn Desktop)
egui = "0.34.2"
eframe = "0.34.2"

# 2. Xử lý logic & AI
lazy_static = "1.5.0"
tract-onnx = "0.22.1" 
ndarray = "0.17.2" 
getrandom = "0.4.2"

# 3. VŨ KHÍ MỚI CHO KIẾN TRÚC CLIENT-SERVER
serde = { version = "1.0", features = ["derive"] } 
serde_json = "1.0"                                 
rayon = "1.10"